name: Deploy Frontend

permissions:
  contents: read

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'src-tauri/**'
      - '.github/assets/**'
      - '.github/workflows/desktop.yml'

jobs:
  build:
    runs-on: cloud
    steps:
      - uses: actions/checkout@v4

      - name: Run Foxogram Frontend
        run: docker compose up -d --build
